"""first migration

Revision ID: 853b753067bc
Revises:
Create Date: 2023-07-30 22:59:16.833425

"""

# revision identifiers, used by Alembic.
revision = "853b753067bc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
